### ISSUE TITLE
Default CSV output breaks Analysis modules

### ISSUE THREAD

**Issue by jvaldezjr1** [davehull/Kansa#134]
Since the new release with the default output as CSV, I've tried to run some analysis scripts and got errors because they are looking for TSV instead.  I can change that with the new flag to return TSV output and should solve things.  However, as the analysis mods are written, some appear to be looking for TSV by default, so there will be a conflict.

<img width="731" alt="screen shot 2015-09-11 at 12 46 17 pm" src="https://cloud.githubusercontent.com/assets/7658588/9823489/d2b37938-5883-11e5-92b2-90cd620a03f2.png">

**Comment by davehull** [comment]
Hm, tough issue here. Get-LogParserStack.ps1 has obviated many of the analysis scripts that were doing stack ranking, but it's currently interactive only, meaning it can't be automated. Best thing is probably to update all of the analysis scripts to default to CSV.

**Comment by davehull** [comment]
I updated all analysis scripts to default to csv input files. If someone is running kansa.ps1 with an outputformat other than csv, they'll have to tweak the analysis scripts. Longer term, the right thing would be to add logic that attempts to detect the format and handles it accordingly.
