### ISSUE TITLE
Kansa Core Bug: Convert-CSV invalid Cmdlet

### ISSUE THREAD

**Issue by jvaldezjr1** [davehull/Kansa#135]
PowerShell v4- got an error when trying to convert output to TSV indicating that `Convert-CSV` is not a valid cmdlet.  I believe the correct cmdlet should be `ConvertTo-CSV` instead.  Changing in my fork and sending a pull request.  Below is the snippet:
```powershell
# save the data
switch -Wildcard ($OutputFormat) {
...
      "*tsv" {
         $Outfile = $Outfile + ".tsv"
          # LogParser can't handle quoted tab separated values, so we'll strip the quotes.
          $Recpt | Convert-Csv -NoTypeInformation -Delimiter "`t" | ForEach-Object { $_ -replace "`"" } | Set-Content -Encoding $Encoding $Outfile
      }
...
```

**Comment by davehull** [comment]
Damn. Nice catch Juan. I've fixed it. This demonstrates the need for something like Pester.
