### ISSUE TITLE
Error: Cannot find any file matching...

### ISSUE THREAD

**Issue by dgriff20** [davehull/Kansa#138]
I keep receiving errors of the nature of
Error: Cannot find any file matching "C:\Windows\system32\*autorunsc.tsv" when running Kansa. These trigger on various modules, causing no output to be generated and eventually Kansa crashes. I am not sure exactly what I am missing or doing wrong here. Any advice on this would be very much appreciated! Thank you!

**Comment by z4ns4tsu** [comment]
Which modules are you running? That sounds like an error the Autoruns analysis modules would throw if you're not in the collector module's output folder.

**Comment by dgriff20** [comment]
I was just running Kansa.ps1. The this particular one hit on 
Get-ASEPImagePathLaunchStringMD5Stack
But there are about 15 others that threw varying versions of this. Sometimes its autorunsc.tsv, others it is SVCFail or svctrigs.

**Comment by davehull** [comment]
Are you running Kansa.ps1 with -pushbin and do you have Autorunsc.exe in your Modules/bin/ folder?

**Comment by davehull** [comment]
Most of the old analysis scripts are deprecated. Don't use them. Use the generic, interactive stack ranking tool in Analysis/Get-LogParserStack.ps1 instead.

**Comment by dgriff20** [comment]
Ok. I will give that a shot. I was just using the instructions off the front page and wasn't sure what I was missing. Thank you.

**Comment by davehull** [comment]
It's probably not you, it's probably the documentation. :)

**Comment by z4ns4tsu** [comment]
This one seems resolved. Closing.
