### ISSUE TITLE
Analysis scripts fail (logparser syntax issue)

### ISSUE THREAD

**Issue by Franky4fngers** [davehull/Kansa#145]
Receiving Error: invalid parameter "fixedsep" on all "Net" analysis scripts.  (likely others)

**Comment by EverythingTxyz** [comment]
Yeah i see it also. using log parser 2.2 I dont think that is a valid command.

**Comment by dry-fly** [comment]
It is valid for the TSV input type, just not for CSV, with LogParser 2.2.  You can edit the analysis ps1 and remove the fixedsep parameter.  You then also need to change the query to look for csv and not tsv files.  It seems like the analysis ps1 scripts were changed to -i:csv but these two apparent corrections were left out?  Not sure whether the get-logparserstack.ps1 is supposed to be a replacement.  It seems that it could be a more generic analysis tool that could work on any data collection types, but currently lacks automation capability.
I'm new to Kansa, just trying it out for the first time.

**Comment by z4ns4tsu** [comment]
Fixed. Thanks for the report.
