### ISSUE TITLE
autorunsc output missing

### ISSUE THREAD

**Issue by theflakes** [davehull/Kansa#149]
Just started working with Kansa.  Thank you all for the hard work on this, really nice.

When I use autorunsc the output returned looks like the below:

"Sysinternals Autoruns v13.62 - Autostart program viewer","PSComputerName","RunspaceId","PSShowComputerName"
"Copyright (C) 2002-2016 Mark Russinovich","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"Sysinternals - www.sysinternals.com","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"Time","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/24/2016 3:54 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"7/15/2016 10:22 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/15/2016 9:10 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"7/15/2016 10:16 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/15/2016 9:10 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"7/15/2016 9:38 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/24/2016 3:26 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"5/31/2016 6:35 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/24/2016 3:26 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"5/31/2016 6:35 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/24/2016 3:26 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"5/31/2016 6:35 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/24/2016 3:26 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"5/31/2016 6:35 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"9/15/2016 9:13 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"7/15/2016 10:17 PM","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"
"","localhost","39db31a4-20c9-44d4-9fdc-f99c3752e37a","True"

I only have the local VM I'm running it on to test with; its Windows 10 Pro.  If I run "Autorunsc.exe /accepteula -a \* -c -h -s '*' 2> $null | ConvertFrom-Csv | ForEach-Object {$_}" in a PS shell I only see date times returned.

If I run "Autorunsc.exe /accepteula -a \* -c -h -s '*' 2> $null" I then see good output.  

Reporting this in case its a bug.  I haven't studied the scripts enough to know if it is or isn't yet.

**Comment by theflakes** [comment]
I submitted a pull request to fix this.  Changed the autorunsc command line in the two relevant modules to:

Autorunsc.exe /accepteula -a * -c -h -s **-nobanner** '*'

**Comment by brianbunke** [comment]
Hi all, I've been looking through the issue log seeing where I may be able to help out. This issue looks like it was resolved in #150, and can probably be closed.

**Comment by athegist** [comment]
I removed the -nobanner flag this morning. It appears to be unsupported in the latest release of autorunsc.exe. If Mark Russinovich keeps moving the goal posts like this, it may make sense long term to have a condition that checks to see if Autorunsc.exe supports -nobanner or not and then call it accordingly, but for now that seems like gold-plating.
